AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Resources for React App Deployment"
Parameters: # params passed to "--parameter-overrides" in CLI
  BucketName:
    Description: Unique name for your bucket.
    Type: String
  RepoName:
    Description: Unique name for your repo.
    Type: String
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket # attach to bucket being created
      PolicyDocument:
        Id: !Join ['', ['S3BucketPolicy', !Ref S3Bucket]]
        Version: 2012-10-17
        Statement: # lets the public access/view the contents of your Bucket, i.e. web app
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*' # wildcard, allow all requests
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, /*]]
  S3BucketCDN:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt 
              - S3Bucket
              - DomainName
            Id: !Join ['', ['S3BucketCDNOrigin', !Ref S3Bucket]]
            S3OriginConfig: {}
        Enabled: 'true'
        DefaultCacheBehavior:
          TargetOriginId: !Join ['', ['S3BucketCDNOrigin', !Ref S3Bucket]]
          ForwardedValues:
            QueryString: 'false'
          ViewerProtocolPolicy: allow-all
  ReactAppAWSRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: This is a repository for the app.
           